spring.application.name=google-oauth2-user-sso


spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}


spring.security.oauth2.client.registration.github.client-id=Ov23liUJ6KY6J3JPSMyY
spring.security.oauth2.client.registration.github.client-secret=7d9a84d0c1e6b8acd613d067ef6ad2826c54d863


logging.level.com.fragma=debug